# Generated by Django 2.0.6 on 2018-06-27 02:19

import dekita.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='todolist',
            name='displayflag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='wayoflearning',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(default=dekita.models.default_category, on_delete=django.db.models.deletion.PROTECT, to='dekita.Category'),
        ),
    ]
